### ISSUE TITLE
Add ability to provide assets rather than loading from FS

### ISSUE THREAD

**Issue by KenSuenobu** [KenSuenobu/rust-pushrod#72]
Add the ability to provide an asset via code rather than having the system manually load the asset on the programmer's behalf.  Modify image_widget and text_widget to support this.  This could eventually apply to the Resource Manager, and ser(de).

**Comment by DoumanAsh** [comment]
To just some thoughts:
The best would be to have ability load resources from slices and any other sources (e.g. Cow) that allows allocation-free for user.

**Comment by KenSuenobu** [comment]
Do you have any code to show an example of possible usage?

**Comment by DoumanAsh** [comment]
The most common scenario would be:

```rust
static FONT: &[u8] = include_bytes!("<font_path>")`

let mut text_widget = TextWidget::new(factory, FONT, "Welcome to rust-pushrod!".to_string(), 32, TextJustify::Left);
```
Where FONT could be transformed into some other type by user, if necessary.

I didn't look how text rending is done internally, but ideally it should be something like that.
Having option to load assets from raw bytes.

Alternatively, maybe it should be possible to register asset globally in pushroad so that it would already have it available instead of loading at runtime.
It could be done like `Pushroad::register_font<'a>(&self, name: Cow<'a, str>, data: Cow<'a, [u8]) -> Result<()>`

**Comment by DoumanAsh** [comment]
@KenSuenobu If you're interested I could try working on it, but it would be better to consider your view on the project.

I think ideally assets should be loaded by user provided asset store/trait that decides how to perform load of assets.
If it would be trait user would be free to implement it himself, so it might bring the better customization.

But I'm not sure how you'd like to see it

**Comment by KenSuenobu** [comment]
@DoumanAsh You can always provide a pull request, and I could do a cherry-pick of the functionality.  I'm going to be adding a caching layer to the system, and something like this could easily help me out.  I want to keep it as simple as possible, though, so the easier to read, the better.  I welcome your contribution, as this is a super useful feature.  (This could even allow embedded images for the ImageButton I plan on adding)

**Comment by KenSuenobu** [comment]
This is not yet possible in Rust. ` lazy_static!` only supports objects that implement `Sync`, of which most of the classes in `Piston` do not.  Therefore, the cache will not be thread-safe.
